#!/usr/bin/env bash
# =============================================================================
# deploy-local.sh — Deploy FHEVM host + MockERC20 + ERC7984ERC20WrapperMock on anvil.
#
# Usage:
#   ./scripts/deploy-local.sh              # anvil must be running on :8545
#   ANVIL_PORT=8546 ./scripts/deploy-local.sh   # custom port
#
# Outputs deployed addresses to stdout and writes scripts/local-addresses.env.
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

ANVIL_PORT="${ANVIL_PORT:-8545}"
RPC_URL="http://127.0.0.1:${ANVIL_PORT}"

# Default anvil account[0] private key
DEPLOYER_PRIVATE_KEY="${DEPLOYER_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"

echo "── deploy-local: checking anvil on port ${ANVIL_PORT}…"
if ! cast chain-id --rpc-url "$RPC_URL" >/dev/null 2>&1; then
  echo "ERROR: anvil not running on ${RPC_URL}. Start it with: anvil --port ${ANVIL_PORT}" >&2
  exit 1
fi

CHAIN_ID="$(cast chain-id --rpc-url "$RPC_URL")"
if [[ "$CHAIN_ID" != "31337" ]]; then
  echo "ERROR: expected chainId 31337, got ${CHAIN_ID}" >&2
  exit 1
fi

# ── Step 1: Deploy FHEVM host (ACL, executor, input verifier, KMS verifier, etc.)
echo "── deploy-local: deploying FHEVM host stack…"
(
  cd evm/lib/forge-fhevm
  DEPLOYER_PRIVATE_KEY="$DEPLOYER_PRIVATE_KEY" \
    ./deploy-local.sh --rpc-url "$RPC_URL" -v
)

echo "── deploy-local: FHEVM host deployed."

# ── Step 2: Deploy MockERC20 + ERC7984ERC20WrapperMock
echo "── deploy-local: deploying MockERC20 + ERC7984ERC20WrapperMock…"

DEPLOY_OUTPUT="$(
  DEPLOYER_PRIVATE_KEY="$DEPLOYER_PRIVATE_KEY" \
  forge script evm/script/DeployLocal.s.sol:DeployLocal \
    --rpc-url "$RPC_URL" \
    --broadcast \
    --private-key "$DEPLOYER_PRIVATE_KEY" \
    2>&1
)"

# Parse deployed addresses from forge script console.log output
UNDERLYING_ADDR="$(echo "$DEPLOY_OUTPUT" | grep 'UNDERLYING:' | awk '{print $NF}')"
TOKEN_ADDR="$(echo "$DEPLOY_OUTPUT" | grep 'TOKEN:' | awk '{print $NF}')"
DEPLOYER_ADDR="$(echo "$DEPLOY_OUTPUT" | grep 'DEPLOYER:' | awk '{print $NF}')"

if [[ -z "$UNDERLYING_ADDR" || -z "$TOKEN_ADDR" ]]; then
  echo "ERROR: Failed to parse deployed addresses from forge output:" >&2
  echo "$DEPLOY_OUTPUT" >&2
  exit 1
fi

# ACL address from forge-fhevm host (matches SDK hardhat preset)
ACL_ADDR="0x50157CFfD6bBFA2DECe204a89ec419c23ef5755D"

# ── Step 3: Quick smoke test — wrap 1 underlying token
echo "── deploy-local: smoke test (approve + wrap)…"
cast send "$UNDERLYING_ADDR" "approve(address,uint256)" "$TOKEN_ADDR" "1000000000000000000" \
  --private-key "$DEPLOYER_PRIVATE_KEY" --rpc-url "$RPC_URL" --gas-limit 100000 >/dev/null
WRAP_TX="$(cast send "$TOKEN_ADDR" "wrap(address,uint256)" "$DEPLOYER_ADDR" "1000000000000000000" \
  --private-key "$DEPLOYER_PRIVATE_KEY" --rpc-url "$RPC_URL" --gas-limit 3000000 --json | jq -r '.transactionHash')"

WRAP_STATUS="$(cast receipt "$WRAP_TX" --rpc-url "$RPC_URL" --json | jq -r '.status')"
if [[ "$WRAP_STATUS" == "0x1" ]]; then
  echo "── deploy-local: ✓ wrap succeeded (tx: ${WRAP_TX})"
else
  echo "── deploy-local: ✗ wrap FAILED (tx: ${WRAP_TX})" >&2
  exit 1
fi

# ── Output
ADDR_FILE="$REPO_ROOT/scripts/local-addresses.env"
cat > "$ADDR_FILE" <<EOF
# Auto-generated by deploy-local.sh — do not edit
TOKEN_ADDRESS=${TOKEN_ADDR}
UNDERLYING_ADDRESS=${UNDERLYING_ADDR}
ACL_ADDRESS=${ACL_ADDR}
DEPLOYER_ADDRESS=${DEPLOYER_ADDR}
EOF

echo ""
echo "═══ Local deployment complete ═══"
echo "  TOKEN_ADDRESS=${TOKEN_ADDR}"
echo "  UNDERLYING_ADDRESS=${UNDERLYING_ADDR}"
echo "  ACL_ADDRESS=${ACL_ADDR}"
echo "  DEPLOYER_ADDRESS=${DEPLOYER_ADDR}"
echo ""
echo "Addresses written to: ${ADDR_FILE}"
echo ""
echo "To use with Ponder/worker/tests:"
echo "  CHAIN=local TOKEN_ADDRESS=${TOKEN_ADDR} UNDERLYING_ADDRESS=${UNDERLYING_ADDR} ACL_ADDRESS=${ACL_ADDR} pnpm dev"
